# Generated by Django 4.2.24 on 2025-09-12 14:42

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_init_flatpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='button_link',
            field=models.CharField(blank=True, max_length=200, validators=[website.models.validate_button_link]),
        ),
    ]
